apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: atlantis-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: atlantis-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    - remoteRef:
        key: atlantis
        property: ARGOCD_INSECURE
      secretKey: ARGOCD_INSECURE
    - remoteRef:
        key: atlantis
        property: ARGOCD_SERVER
      secretKey: ARGOCD_SERVER
    - remoteRef:
        key: atlantis
        property: ARGO_SERVER_URL
      secretKey: ARGO_SERVER_URL
    - remoteRef:
        key: atlantis
        property: ATLANTIS_GITLAB_USER
      secretKey: ATLANTIS_GITLAB_USER
    - remoteRef:
        key: atlantis
        property: ATLANTIS_GITLAB_HOSTNAME
      secretKey: ATLANTIS_GITLAB_HOSTNAME
    - remoteRef:
        key: atlantis
        property: ATLANTIS_GITLAB_TOKEN
      secretKey: ATLANTIS_GITLAB_TOKEN
#     - remoteRef:
#         key: atlantis
#         property: AWS_DEFAULT_REGION
#       secretKey: AWS_DEFAULT_REGION
#     - remoteRef:
#         key: atlantis
#         property: AWS_ROLE_TO_ASSUME
#       secretKey: AWS_ROLE_TO_ASSUME
#     - remoteRef:
#         key: atlantis
#         property: AWS_SESSION_NAME
#       secretKey: AWS_SESSION_NAME
    - remoteRef:
        key: atlantis
        property: GITLAB_BASE_URL
      secretKey: GITLAB_BASE_URL
    - remoteRef:
        key: atlantis
        property: GITLAB_TOKEN
      secretKey: GITLAB_TOKEN
    - remoteRef:
        key: atlantis
        property: KUBECONFIG
      secretKey: KUBECONFIG    
    - remoteRef:
        key: atlantis
        property: TF_VAR_argo_redirect_uris
      secretKey: TF_VAR_argo_redirect_uris
    - remoteRef:
        key: atlantis
        property: TF_VAR_argocd_redirect_uris
      secretKey: TF_VAR_argocd_redirect_uris
    - remoteRef:
        key: atlantis
        property: TF_VAR_aws_account_id
      secretKey: TF_VAR_aws_account_id
    - remoteRef:
        key: atlantis
        property: TF_VAR_aws_region
      secretKey: TF_VAR_aws_region      
    - remoteRef:
        key: atlantis
        property: TF_VAR_email_address
      secretKey: TF_VAR_email_address
    - remoteRef:
        key: atlantis
        property: TF_VAR_gitlab_redirect_uris
      secretKey: TF_VAR_gitlab_redirect_uris
    - remoteRef:
        key: atlantis
        property: TF_VAR_gitlab_runner_token
      secretKey: TF_VAR_gitlab_runner_token
    - remoteRef:
        key: atlantis
        property: TF_VAR_gitlab_token
      secretKey: TF_VAR_gitlab_token
    - remoteRef:
        key: atlantis
        property: TF_VAR_gitlab_url
      secretKey: TF_VAR_gitlab_url
    - remoteRef:
        key: atlantis
        property: TF_VAR_hosted_zone_id
      secretKey: TF_VAR_hosted_zone_id
    - remoteRef:
        key: atlantis
        property: TF_VAR_hosted_zone_name
      secretKey: TF_VAR_hosted_zone_name
    - remoteRef:
        key: atlantis
        property: TF_VAR_vault_addr
      secretKey: TF_VAR_vault_addr
    - remoteRef:
        key: atlantis
        property: TF_VAR_vault_redirect_uris
      secretKey: TF_VAR_vault_redirect_uris
    - remoteRef:
        key: atlantis
        property: TF_VAR_vault_token
      secretKey: TF_VAR_vault_token
    - remoteRef:
        key: atlantis
        property: VAULT_TOKEN
      secretKey: VAULT_TOKEN
    - remoteRef:
        key: atlantis
        property: VAULT_ADDR
      secretKey: VAULT_ADDR
