apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: atlantis-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    name: atlantis-secrets
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  refreshInterval: 10s
  data:
    - remoteRef:
        key: atlantis
        property: atlantis
