apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://gitlab.<AWS_HOSTED_ZONE>/kubefirst/gitops.git
    path: components/argo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "8"
subjects:
- kind: ServiceAccount
  name: argocd
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "9"
subjects:
- kind: ServiceAccount
  name: argo
  namespace: argo
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

