apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: https://gitlab.jessica.kube1st.com/kubefirst/gitops.git
    path: components/console
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: console
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true