apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-for-gitlab
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: default
  source:
    repoURL: ssh://soft-serve.soft-serve.svc.cluster.local:22/gitops
    path: components/external-secrets-for-gitlab
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
