apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-github
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: registry/github
    repoURL: git@github.com:<ORG>/<REPO_GITOPS>.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m0s
      limit: 5
    syncOptions:
    - CreateNamespace=true
    
