apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubefirst.github.io/charts
    targetRevision: 0.2.4
    chart: console
    helm:
      values: |-
        env:
          HOSTED_ZONE_NAME:
            value: "<AWS_HOSTED_ZONE_NAME>"
          GITHUB_HOST:
            value: "<GITHUB_HOST>"
          GITHUB_OWNER:
            value: "<GITHUB_OWNER>"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: kubefirst.<AWS_HOSTED_ZONE_NAME>
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: kubefirst-tls
              hosts:
                - kubefirst.<AWS_HOSTED_ZONE_NAME>
  destination:
    server: https://kubernetes.default.svc
    namespace: console
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true