apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-runner
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: github-runner
spec:
  target:
    name: controller-manager
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secrets-backend
  data:
  - remoteRef:
      key: ci-secrets
      property: PERSONAL_ACCESS_TOKEN
    secretKey: github_token
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-kubefirst
spec:
  # This will deploy 2 runners now
  replicas: 1
  template:
    spec:  
      organization: <GITHUB_ORG>
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
