apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusk-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubeshop.github.io/helm-charts
    chart: kusk-gateway
    targetRevision: 0.0.44
  destination:
    server: https://kubernetes.default.svc
    namespace: kusk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true